window.DEPORTIVO26_DATA = {
  "torneo": {
    "nombre": "ESTATAL INTERCOBAT 2026",
    "subtitulo": "Rol de Juegos Estatal Deportivo 2026",
    "fechas": "Martes 29, Miércoles 30 de Septiembre y Jueves 1 de Octubre de 2026",
    "lugar": "Instalaciones Deportivas Estatales / CAR"
  },
  "planteles": [
    "PLANTEL 01",
    "PLANTEL 02",
    "PLANTEL 03",
    "PLANTEL 04",
    "PLANTEL 05",
    "PLANTEL 07",
    "PLANTEL 08",
    "PLANTEL 10",
    "PLANTEL 13",
    "PLANTEL 15",
    "PLANTEL 16",
    "PLANTEL 17",
    "PLANTEL 18",
    "PLANTEL 20",
    "PLANTEL 22",
    "CEMSADET 03",
    "CEMSADET 04",
    "CEMSADET 13",
    "TEBA 35"
  ],
  "grupos": {
    "Fútbol": {
      "Varonil": {
        "Grupo A": [
          "PLANTEL 15",
          "PLANTEL 20",
          "PLANTEL 22",
          "PLANTEL 05"
        ],
        "Grupo B": [
          "PLANTEL 18",
          "PLANTEL 02",
          "PLANTEL 03",
          "PLANTEL 10"
        ]
      },
      "Femenil": {
        "Grupo A": [
          "PLANTEL 02",
          "PLANTEL 08",
          "PLANTEL 03",
          "CEMSADET 13"
        ],
        "Grupo B": [
          "PLANTEL 10",
          "CEMSADET 03",
          "PLANTEL 01"
        ]
      }
    },
    "Voleibol": {
      "Varonil": {
        "Grupo A": [
          "PLANTEL 16",
          "PLANTEL 17",
          "PLANTEL 01",
          "PLANTEL 13"
        ],
        "Grupo B": [
          "CEMSADET 03",
          "PLANTEL 20",
          "CEMSADET 04",
          "PLANTEL 02"
        ]
      },
      "Femenil": {
        "Grupo A": [
          "PLANTEL 17",
          "PLANTEL 20",
          "CEMSADET 04",
          "PLANTEL 16"
        ],
        "Grupo B": [
          "PLANTEL 13",
          "PLANTEL 05",
          "PLANTEL 02",
          "PLANTEL 01"
        ]
      }
    },
    "Basquetbol": {
      "Varonil": {
        "Grupo A": [
          "PLANTEL 05",
          "PLANTEL 16",
          "PLANTEL 22",
          "PLANTEL 02"
        ],
        "Grupo B": [
          "PLANTEL 01",
          "PLANTEL 04",
          "TEBA 35"
        ]
      },
      "Femenil": {
        "Grupo Único": [
          "PLANTEL 02",
          "PLANTEL 04",
          "PLANTEL 22",
          "TEBA 35"
        ]
      }
    },
    "Tochito": {
      "Varonil": {
        "Serie Final": [
          "PLANTEL 02",
          "PLANTEL 01"
        ]
      },
      "Femenil": {
        "Grupo Único": [
          "PLANTEL 02",
          "PLANTEL 01",
          "PLANTEL 07",
          "PLANTEL 05"
        ]
      }
    }
  },
  "criterios": {
    "Fútbol": [
      "Puntos obtenidos en fase de grupos.",
      "Diferencia de goles.",
      "Resultado directo entre empatados."
    ],
    "Voleibol": [
      "1. Partidos ganados.",
      "2. Diferencia de puntos.",
      "3. Diferencia de sets.",
      "4. Resultado entre los equipos empatados.",
      "5. Sorteo, como último recurso."
    ],
    "Basquetbol": [
      "Tabla de posiciones por victorias.",
      "Procedimiento de empate: Si finaliza empatado a los 60 min reglamentarios, se concede descanso de 2 min y prórroga de 5 min sucesivamente hasta haber un ganador."
    ],
    "Tochito": [
      "1. Número de victorias.",
      "2. Resultado entre los equipos empatados.",
      "3. Diferencia de puntos (anotados - recibidos).",
      "4. Puntos anotados.",
      "5. Menor cantidad de puntos recibidos.",
      "6. Sorteo si el empate persiste."
    ]
  },
  "partidos": [
    {
      "id": 1,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "08:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 15",
      "equipo2": "PLANTEL 20"
    },
    {
      "id": 2,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "10:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 22",
      "equipo2": "PLANTEL 05"
    },
    {
      "id": 3,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "16:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 15",
      "equipo2": "PLANTEL 22"
    },
    {
      "id": 4,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "17:50",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 20",
      "equipo2": "PLANTEL 05"
    },
    {
      "id": 5,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "08:00",
      "cancha": "Cancha 2",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 18",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 6,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "10:00",
      "cancha": "Cancha 2",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 03",
      "equipo2": "PLANTEL 10"
    },
    {
      "id": 7,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "16:00",
      "cancha": "Cancha 2",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 18",
      "equipo2": "PLANTEL 03"
    },
    {
      "id": 8,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "17:50",
      "cancha": "Cancha 2",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 10"
    },
    {
      "id": 9,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "08:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 15",
      "equipo2": "PLANTEL 05"
    },
    {
      "id": 10,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "10:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 20",
      "equipo2": "PLANTEL 22"
    },
    {
      "id": 11,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "08:00",
      "cancha": "Cancha 2",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 18",
      "equipo2": "PLANTEL 10"
    },
    {
      "id": 12,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "10:00",
      "cancha": "Cancha 2",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 03"
    },
    {
      "id": 13,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "16:00",
      "cancha": "Cancha 1",
      "fase": "3er Lugar",
      "grupo": "3er Lugar",
      "equipo1": "2º GRUPO V-A",
      "equipo2": "2º GRUPO V-B"
    },
    {
      "id": 14,
      "deporte": "Fútbol",
      "rama": "Varonil",
      "dia": "Jueves 1 de Octubre",
      "fecha_corta": "01/10",
      "hora": "09:00",
      "cancha": "Cancha 1",
      "fase": "Final",
      "grupo": "Final",
      "equipo1": "1º GRUPO V-A",
      "equipo2": "1º GRUPO V-B"
    },
    {
      "id": 15,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "08:00",
      "cancha": "Cancha 4",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 08"
    },
    {
      "id": 16,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "10:00",
      "cancha": "Cancha 4",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 03",
      "equipo2": "CEMSADET 13"
    },
    {
      "id": 17,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "16:00",
      "cancha": "Cancha 4",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 03"
    },
    {
      "id": 18,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "17:50",
      "cancha": "Cancha 4",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 08",
      "equipo2": "CEMSADET 13"
    },
    {
      "id": 19,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "08:00",
      "cancha": "Cancha 5",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 10",
      "equipo2": "CEMSADET 03",
      "notas": "Descansa PLANTEL 01"
    },
    {
      "id": 20,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "17:00",
      "cancha": "Cancha 5",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 10",
      "equipo2": "PLANTEL 01",
      "notas": "Descansa CEMSADET 03"
    },
    {
      "id": 21,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "08:00",
      "cancha": "Cancha 4",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 02",
      "equipo2": "CEMSADET 13"
    },
    {
      "id": 22,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "10:00",
      "cancha": "Cancha 4",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 08",
      "equipo2": "PLANTEL 03"
    },
    {
      "id": 23,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "08:00",
      "cancha": "Cancha 5",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "CEMSADET 03",
      "equipo2": "PLANTEL 01"
    },
    {
      "id": 24,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "16:00",
      "cancha": "Cancha 4",
      "fase": "3er Lugar",
      "grupo": "3er Lugar",
      "equipo1": "2º GRUPO F-A",
      "equipo2": "2º GRUPO F-B"
    },
    {
      "id": 25,
      "deporte": "Fútbol",
      "rama": "Femenil",
      "dia": "Jueves 1 de Octubre",
      "fecha_corta": "01/10",
      "hora": "09:00",
      "cancha": "Cancha 2",
      "fase": "Final",
      "grupo": "Final",
      "equipo1": "1º GRUPO F-A",
      "equipo2": "1º GRUPO F-B"
    },
    {
      "id": 26,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "08:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 1",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 16",
      "equipo2": "PLANTEL 17"
    },
    {
      "id": 27,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "08:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 1",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 17",
      "equipo2": "PLANTEL 20"
    },
    {
      "id": 28,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "09:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 2",
      "grupo": "Grupo B",
      "equipo1": "CEMSADET 03",
      "equipo2": "PLANTEL 20"
    },
    {
      "id": 29,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "09:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 2",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 13",
      "equipo2": "PLANTEL 05"
    },
    {
      "id": 30,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "10:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 3",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 01",
      "equipo2": "PLANTEL 13"
    },
    {
      "id": 31,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "10:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 3",
      "grupo": "Grupo A",
      "equipo1": "CEMSADET 04",
      "equipo2": "PLANTEL 16"
    },
    {
      "id": 32,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "11:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 4",
      "grupo": "Grupo B",
      "equipo1": "CEMSADET 04",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 33,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "11:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 4",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 01"
    },
    {
      "id": 34,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "12:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 5",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 17",
      "equipo2": "PLANTEL 13"
    },
    {
      "id": 35,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "12:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 5",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 20",
      "equipo2": "PLANTEL 16"
    },
    {
      "id": 36,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "14:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 6",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 20",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 37,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "14:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 6",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 05",
      "equipo2": "PLANTEL 01"
    },
    {
      "id": 38,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "09:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 7",
      "grupo": "Grupo B",
      "equipo1": "CEMSADET 03",
      "equipo2": "CEMSADET 04"
    },
    {
      "id": 39,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "09:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 7",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 13",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 40,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "10:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 8",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 16",
      "equipo2": "PLANTEL 01"
    },
    {
      "id": 41,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "10:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 8",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 17",
      "equipo2": "CEMSADET 04"
    },
    {
      "id": 42,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "11:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 9",
      "grupo": "Grupo B",
      "equipo1": "CEMSADET 03",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 43,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "11:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 9",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 13",
      "equipo2": "PLANTEL 01"
    },
    {
      "id": 44,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "12:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 10",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 16",
      "equipo2": "PLANTEL 13"
    },
    {
      "id": 45,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "12:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 10",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 17",
      "equipo2": "PLANTEL 16"
    },
    {
      "id": 46,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "13:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 11",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 17",
      "equipo2": "PLANTEL 01"
    },
    {
      "id": 47,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "13:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 11",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 20",
      "equipo2": "CEMSADET 04"
    },
    {
      "id": 48,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "14:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 12",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 20",
      "equipo2": "CEMSADET 04"
    },
    {
      "id": 49,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "14:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 12",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 05",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 50,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Jueves 1 de Octubre",
      "fecha_corta": "01/10",
      "hora": "09:00",
      "cancha": "Cancha 1",
      "fase": "3er Lugar",
      "grupo": "3er Lugar",
      "equipo1": "2º GRUPO A",
      "equipo2": "2º GRUPO B"
    },
    {
      "id": 51,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Jueves 1 de Octubre",
      "fecha_corta": "01/10",
      "hora": "09:00",
      "cancha": "Cancha 2",
      "fase": "3er Lugar",
      "grupo": "3er Lugar",
      "equipo1": "2º GRUPO A",
      "equipo2": "2º GRUPO B"
    },
    {
      "id": 52,
      "deporte": "Voleibol",
      "rama": "Varonil",
      "dia": "Jueves 1 de Octubre",
      "fecha_corta": "01/10",
      "hora": "10:00",
      "cancha": "Cancha 1",
      "fase": "Final",
      "grupo": "Final",
      "equipo1": "1º GRUPO A",
      "equipo2": "1º GRUPO B"
    },
    {
      "id": 53,
      "deporte": "Voleibol",
      "rama": "Femenil",
      "dia": "Jueves 1 de Octubre",
      "fecha_corta": "01/10",
      "hora": "10:00",
      "cancha": "Cancha 2",
      "fase": "Final",
      "grupo": "Final",
      "equipo1": "1º GRUPO A",
      "equipo2": "1º GRUPO B"
    },
    {
      "id": 54,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "09:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 05",
      "equipo2": "PLANTEL 16"
    },
    {
      "id": 55,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "10:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 01",
      "equipo2": "PLANTEL 04"
    },
    {
      "id": 56,
      "deporte": "Basquetbol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "11:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 04"
    },
    {
      "id": 57,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "12:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 22",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 58,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "13:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 04",
      "equipo2": "TEBA 35"
    },
    {
      "id": 59,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "14:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 05",
      "equipo2": "PLANTEL 22"
    },
    {
      "id": 60,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "15:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 16",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 61,
      "deporte": "Basquetbol",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "16:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 22",
      "equipo2": "TEBA 35"
    },
    {
      "id": 62,
      "deporte": "Basquetbol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "09:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 22"
    },
    {
      "id": 63,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "10:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo B",
      "equipo1": "PLANTEL 01",
      "equipo2": "TEBA 35"
    },
    {
      "id": 64,
      "deporte": "Basquetbol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "11:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 04",
      "equipo2": "TEBA 35"
    },
    {
      "id": 65,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "12:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 05",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 66,
      "deporte": "Basquetbol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "13:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 02",
      "equipo2": "TEBA 35"
    },
    {
      "id": 67,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "14:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo A",
      "equipo1": "PLANTEL 16",
      "equipo2": "PLANTEL 22"
    },
    {
      "id": 68,
      "deporte": "Basquetbol",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "15:00",
      "cancha": "Cancha 1",
      "fase": "Fase de Grupos",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 04",
      "equipo2": "PLANTEL 22"
    },
    {
      "id": 69,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Jueves 1 de Octubre",
      "fecha_corta": "01/10",
      "hora": "09:00",
      "cancha": "Cancha 1",
      "fase": "3er Lugar",
      "grupo": "3er Lugar",
      "equipo1": "2º GRUPO A",
      "equipo2": "2º GRUPO B"
    },
    {
      "id": 70,
      "deporte": "Basquetbol",
      "rama": "Varonil",
      "dia": "Jueves 1 de Octubre",
      "fecha_corta": "01/10",
      "hora": "10:00",
      "cancha": "Cancha 1",
      "fase": "Final",
      "grupo": "Final",
      "equipo1": "1º GRUPO A",
      "equipo2": "1º GRUPO B"
    },
    {
      "id": 71,
      "deporte": "Tochito",
      "rama": "Varonil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "16:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 1",
      "grupo": "Serie Final",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 01"
    },
    {
      "id": 72,
      "deporte": "Tochito",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "17:00",
      "cancha": "Cancha 2",
      "fase": "Jornada 1",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 07",
      "equipo2": "PLANTEL 01"
    },
    {
      "id": 73,
      "deporte": "Tochito",
      "rama": "Femenil",
      "dia": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "hora": "18:00",
      "cancha": "Cancha 3",
      "fase": "Jornada 1",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 01",
      "equipo2": "PLANTEL 05"
    },
    {
      "id": 74,
      "deporte": "Tochito",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "08:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 2",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 01",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 75,
      "deporte": "Tochito",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "09:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 2",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 07",
      "equipo2": "PLANTEL 05"
    },
    {
      "id": 76,
      "deporte": "Tochito",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "10:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 2",
      "grupo": "Serie Final",
      "equipo1": "PLANTEL 01",
      "equipo2": "PLANTEL 02"
    },
    {
      "id": 77,
      "deporte": "Tochito",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "11:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 2",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 07"
    },
    {
      "id": 78,
      "deporte": "Tochito",
      "rama": "Femenil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "12:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 2",
      "grupo": "Grupo Único",
      "equipo1": "PLANTEL 01",
      "equipo2": "PLANTEL 05"
    },
    {
      "id": 79,
      "deporte": "Tochito",
      "rama": "Varonil",
      "dia": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "hora": "13:00",
      "cancha": "Cancha 1",
      "fase": "Jornada 2 (Desempate)",
      "grupo": "Serie Final",
      "equipo1": "PLANTEL 02",
      "equipo2": "PLANTEL 01",
      "notas": "Se juega si están empatados 1-1"
    }
  ],
  "atletismo": [
    {
      "id": 101,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "08:00",
      "num_evento": "101",
      "prueba": "3,000 metros planos",
      "rama": "Femenil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 104,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "08:30",
      "num_evento": "104",
      "prueba": "5,000 metros planos",
      "rama": "Varonil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 105,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "09:00",
      "num_evento": "105",
      "prueba": "100 metros planos",
      "rama": "Femenil",
      "atletas": 16,
      "fase": "Eliminatoria"
    },
    {
      "id": 106,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "09:15",
      "num_evento": "106",
      "prueba": "100 metros planos",
      "rama": "Varonil",
      "atletas": 16,
      "fase": "Eliminatoria"
    },
    {
      "id": 107,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "09:30",
      "num_evento": "107",
      "prueba": "800 metros planos",
      "rama": "Femenil",
      "atletas": 16,
      "fase": "Final Contra Reloj"
    },
    {
      "id": 108,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "09:45",
      "num_evento": "108",
      "prueba": "800 metros planos",
      "rama": "Varonil",
      "atletas": 16,
      "fase": "Final Contra Reloj"
    },
    {
      "id": 109,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "10:20",
      "num_evento": "109",
      "prueba": "100 metros planos",
      "rama": "Femenil",
      "atletas": 8,
      "fase": "Final"
    },
    {
      "id": 110,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "10:30",
      "num_evento": "110",
      "prueba": "100 metros planos",
      "rama": "Varonil",
      "atletas": 8,
      "fase": "Final"
    },
    {
      "id": 102,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Campo CAR",
      "tipo": "Campo",
      "hora": "08:00",
      "num_evento": "102",
      "prueba": "Impulso de Bala 3kg",
      "rama": "Femenil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 103,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Campo CAR",
      "tipo": "Campo",
      "hora": "08:00",
      "num_evento": "103",
      "prueba": "Salto de Longitud",
      "rama": "Varonil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 1052,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "Campo CAR",
      "tipo": "Campo",
      "hora": "10:00",
      "num_evento": "105-C",
      "prueba": "Impulso de Bala 5kg",
      "rama": "Varonil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 999,
      "sesion": "Sesión 1",
      "fecha": "Martes 29 de Septiembre",
      "fecha_corta": "29/09",
      "lugar": "CAR",
      "tipo": "Premiación",
      "hora": "12:00",
      "num_evento": "PREM",
      "prueba": "Protocolo de Premiación de Pruebas Finales",
      "rama": "Mixto",
      "atletas": 0,
      "fase": "Premiación"
    },
    {
      "id": 111,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "08:00",
      "num_evento": "111",
      "prueba": "200 metros planos",
      "rama": "Femenil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 113,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "08:15",
      "num_evento": "113",
      "prueba": "200 metros planos",
      "rama": "Varonil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 114,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "08:45",
      "num_evento": "114",
      "prueba": "1,500 metros planos",
      "rama": "Femenil",
      "atletas": 16,
      "fase": "Eliminatoria"
    },
    {
      "id": 115,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "09:00",
      "num_evento": "115",
      "prueba": "1,500 metros planos",
      "rama": "Varonil",
      "atletas": 16,
      "fase": "Eliminatoria"
    },
    {
      "id": 117,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "09:20",
      "num_evento": "117",
      "prueba": "400 metros planos",
      "rama": "Femenil",
      "atletas": 16,
      "fase": "Final Contra Reloj"
    },
    {
      "id": 118,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "09:30",
      "num_evento": "118",
      "prueba": "400 metros planos",
      "rama": "Varonil",
      "atletas": 16,
      "fase": "Final Contra Reloj"
    },
    {
      "id": 119,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "10:00",
      "num_evento": "119",
      "prueba": "200 metros planos",
      "rama": "Femenil",
      "atletas": 8,
      "fase": "Final"
    },
    {
      "id": 121,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Pista CAR",
      "tipo": "Pista",
      "hora": "10:10",
      "num_evento": "121",
      "prueba": "200 metros planos",
      "rama": "Varonil",
      "atletas": 8,
      "fase": "Final"
    },
    {
      "id": 112,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Campo CAR",
      "tipo": "Campo",
      "hora": "08:00",
      "num_evento": "112",
      "prueba": "Salto de Longitud",
      "rama": "Femenil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 116,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Campo CAR",
      "tipo": "Campo",
      "hora": "08:00",
      "num_evento": "116",
      "prueba": "Lanzamiento del Disco 1kg",
      "rama": "Femenil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 120,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "Campo CAR",
      "tipo": "Campo",
      "hora": "10:00",
      "num_evento": "120",
      "prueba": "Lanzamiento del Disco 1.5kg",
      "rama": "Varonil",
      "atletas": 16,
      "fase": "Final"
    },
    {
      "id": 998,
      "sesion": "Sesión 2",
      "fecha": "Miércoles 30 de Septiembre",
      "fecha_corta": "30/09",
      "lugar": "CAR",
      "tipo": "Premiación",
      "hora": "12:00",
      "num_evento": "PREM2",
      "prueba": "Protocolo de Premiación de Pruebas Finales",
      "rama": "Mixto",
      "atletas": 0,
      "fase": "Premiación"
    }
  ]
};